apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app-prod
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm-charts/my-app
    repoURL: "git@github.com:Lucas-Andrade-pc/eks-argocd.git"
    targetRevision: main
    source:
    helm:
      parameters:
      - name: image.repository
        value: 957535344733.dkr.ecr.us-east-1.amazonaws.com/my-app
      - name: service.port
        value: '8085'
      - name: livenessProbe.httpGet.path
        value: /health
      - name: readinessProbe.httpGet.path
        value: /health
      - name: image.tag
        value: 0.1.0
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true